---
extends: default
rules:
  line-length:
    max: 200
  braces:
    max-spaces-inside: 1
    level: error
  brackets:
    max-spaces-inside: 1
    level: error
  comments:
    min-spaces-from-content: 1
  comments-indentation: false
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: true
  truthy:
    allowed-values:
      - 'true'
      - 'yes'
      - 'false'
      - 'no'
    ignore:
      # vim-ale seems to not like full paths...probably a bug
      # - .github/workflows/
      - ci.yml
