---
- name: Create SSH directory for root
  file:
    path: /root/.ssh/
    state: directory
    mode: 0700

- name: Create root SSH key pair for PVE
  user:
    name: root
    generate_ssh_key: yes
    ssh_key_file: /root/.ssh/id_rsa
    ssh_key_type: rsa
    ssh_key_comment: "root@{{ inventory_hostname_short }}"

- name: Fetch root SSH public key
  slurp:
    src: /root/.ssh/id_rsa.pub
  register: proxmox_root_id_rsa_pub

- name: Accumulate all hosts' root SSH public keys
  set_fact:
    _pve_root_ssh_pubkeys: "{{ _pve_root_ssh_pubkeys | default([]) | union([hostvars[item].proxmox_root_id_rsa_pub.content | b64decode]) }}"
  with_items: "{{ groups[pve_group] }}"

- name: Authorize SSH public keys for root user
  authorized_key:
    user: root
    key: "{{ pve_ssh_extra_keys | default([]) | union(_pve_root_ssh_pubkeys) | join('\n') }}"
    exclusive: "{{ pve_ssh_extra_keys | default([]) | length > 0 }}"