---
name: publish role on galaxy

on:
  push:
    branches:
      - main
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: hspaans/ansible-galaxy-action@e8e53e52c543ae3b0082a3eb46ae326fa044affb # v2.1.1
        with:
          api_key: ${{ secrets.MILKY_WAY }}
