---
name: lints, lints, lints
on:
  pull_request: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  ansible-lint:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.14"
          cache: "pip"
          # since this isn't exactly a python project, have it "kind" of depend on modifications
          # to this file (which should only matter when the ansible-lint version changes)
          cache-dependency-path: requirements-dev.txt
      - uses: idolactivities/action-ansiblelint@0fa32fc70e0e2d03960332cf1a33ad8defe1f30e
        with:
          filter_mode: "diff_context"
          ansiblelint_version: 26.4.0
